### ISSUE TITLE
Switching between 2 monitors?

### ISSUE THREAD

**Issue by Stata-by-voice** [h2ero/XEasyMotion#10]
Thank you for providing this great code to the community. It is a really cool project.

I might've missed it somewhere, but is there a way to switch between dual monitors? The grid seems to open in whichever monitor the mouse was in last.

**Comment by makerneo-com** [comment]
Good idea. I will add it in the future

**Comment by colossatr0n** [comment]
@Stata-by-voice Look into using https://github.com/koekeishiya/yabai for switching between monitors. It's a tiling manager and would work great in this situation.
