### ISSUE TITLE
App does not exit after completing an action, and cannot be run again until killed

### ISSUE THREAD

**Issue by CRThaze** [h2ero/XEasyMotion#11]
OS: macOS Sierra 10.12.6
XEasyMotion: 0.1.2

I can launch the application successfully once.  However after using the first time it will not open again until I run 'killall XEasyMotion' in the terminal.  The application does not appear in the ForceQuit menu prior to this either.

**Comment by CRThaze** [comment]
In the meantime I've added a step to the macOS service I'm using to launch XEasyMotion which will automatically perform this 'killall' step after 5 seconds.

**Comment by makerneo-com** [comment]
Try v0.1.3 , I run it on macOS 10.13  is OK

https://github.com/h2ero/XEasyMotion/releases/tag/v0.1.3

**Comment by santhosh82** [comment]
@CRThaze How do we run/install the application?
