### ISSUE TITLE
List compatibility with os version / hardware ? 

### ISSUE THREAD

**Issue by m-gris** [h2ero/XEasyMotion#23]
Hi, 

I was very excited when I discovered your app. However when I tried to install it, I ran into: 

> "You can’t open the application “XEasyMotion” because this application is not supported on this Mac."

**Config**
Hardware: MacBook Pro (15-inch, 2018)
macOS version: Monterey 

It could be nice if the README also included a list of compatibility :)  

By any chance, is there an update "in the pipe" that will make your app compatible with the config above ?  

Thx 
M.

**Comment by makerneo-com** [comment]
I have rebuild binary for apple silicon and intel chip, you can download it https://github.com/h2ero/XEasyMotion/releases/tag/v2.1


https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary

**Comment by m-gris** [comment]
> I have rebuild binary for apple silicon and intel chip, you can download it https://github.com/h2ero/XEasyMotion/releases/tag/v2.1
> 
> https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary

Thx ! (and sorry for the late reply)
