### ISSUE TITLE
Does not work on macOS Ventura

### ISSUE THREAD

**Issue by joobus** [h2ero/XEasyMotion#24]
I upgraded to Ventura a couple days ago.  I was using xEasyMotion 0.1.3 at the time.  I was able to pull up the grid with `cmd+i`, but on hitting enter no click would register and the grid would stay on the screen.  I downloaded and installed the most recent release (0.1.4?), and the same issue persisted, but with 0.1.4 I also could not right click the icon in the top menu bar to quit the application.

This is on a 2019 Macbook Pro (intel).

**Comment by nagakirankys** [comment]
Found https://github.com/rvaiya/warpd provides same functionality and some extra modes also.
