### ISSUE TITLE
Use NSUserDefaults instead of .xeasymotionrc

### ISSUE THREAD

**Issue by tweekmonster** [h2ero/XEasyMotion#4]
I was just trying out the latest changes.  It took me a little while to figure out I needed to have an `.xeasymotionrc` file and the `Yaml` framework.  I think `NSUserDefaults` should be used instead since it's an expected way to store configurations on OS X.  It's well supported by the core framework which would make it easier to create a preferences window.

I also think that OS X GUI apps shouldn't clutter the `$HOME` directory with dot files.  If they must, they should at least conform to the [XDG Base Directory spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

**Comment by makerneo-com** [comment]
good idea.
I don't know NSUserDefaults to store data into *.plist  in the past.

**Comment by tweekmonster** [comment]
It's been a while since I developed for OS X, but I think you can have a default plist bundled with the app.  You can also bind the view states to it as well.  It makes it much easier to manage default settings for the app.
