### ISSUE TITLE
.xeasymotionrc doesn't seem to be read

### ISSUE THREAD

**Issue by escherdragon** [h2ero/XEasyMotion#6]
Hello h2ero.
In the first place thank you very much for writing keynav for OSX.
I'm having a small problem with the latest version: it seems that the configuration file (.xeasymotionrc) is not being read at all. I've copied verbatim the provided example in my home directory and given it 644 access privileges, but even the simplest changes (e.g. changing the line color from #f00 to #00f) don't effect in any way the program at runtime. Is there anything else I should do to make it work?
## Cheers,

José A. Romero L.
escherdragon@gmail.com

**Comment by makerneo-com** [comment]
Hi escherdragon
Configuration file feature has not been completed.   : (
I will make it work in the future. refer to this issue #4

**Comment by escherdragon** [comment]
I see. Looking forward to it, then. Thanks a lot.
